on:
  push:
    branches-ignore:
      - 'ga-ignore-'
  pull_request:
    branches-ignore:
      - 'ga-ignore-'

env:
  MIRROR_URL: git@github.com:SIMLUKE/actions_playground_mirror.git

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
    - uses: actions/checkout@v3
    - name: Run coding style
      run: check.sh . .
  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make
    - name: Run_tests
      run: make tests_run
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            $MIRROR_URL
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
